runtime: nodejs

env: flex

env_variables:
  HOST: "0.0.0.0"
  NODE_ENV: "production"
  DATABASE_NAME: "strapi"
  DATABASE_USERNAME: "postgres"
  DATABASE_PASSWORD: "Dazza0510!"
  INSTANCE_CONNECTION_NAME: "creative-milk:australia-southeast2:myinstance"

beta_settings:
  cloud_sql_instances: "creative-milk:australia-southeast2:myinstance"
